# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSbj.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, localeDATA):
        self.localeDATA = localeDATA
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.subjectList = QtWidgets.QListWidget(Form)
        self.subjectList.setGeometry(QtCore.QRect(0, 0, 401, 251))
        self.subjectList.setObjectName("subjectList")
        self.addSubject = QtWidgets.QPushButton(Form)
        self.addSubject.setGeometry(QtCore.QRect(130, 260, 75, 23))
        self.addSubject.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addSubject.setObjectName("addSubject")
        self.createSubject = QtWidgets.QPushButton(Form)
        self.createSubject.setGeometry(QtCore.QRect(200, 260, 31, 23))
        self.createSubject.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createSubject.setObjectName("createSubject")
        self.rmSubject = QtWidgets.QPushButton(Form)
        self.rmSubject.setGeometry(QtCore.QRect(230, 260, 31, 23))
        self.rmSubject.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rmSubject.setObjectName("rmSubject")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", self.localeDATA['add_subject']))
        self.addSubject.setText(_translate("Form", self.localeDATA['add_text']))
        self.createSubject.setText(_translate("Form", "+"))
        self.rmSubject.setText(_translate("Form", "-"))
import source_rc
