# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lessonCreate.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, localeDATA):
        self.localeDATA = localeDATA
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(386, 249)
        Form.setMinimumSize(QtCore.QSize(386, 249))
        Form.setMaximumSize(QtCore.QSize(386, 249))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.teacherName = QtWidgets.QLineEdit(Form)
        self.teacherName.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.teacherName.setObjectName("teacherName")
        self.lessonName = QtWidgets.QLineEdit(Form)
        self.lessonName.setGeometry(QtCore.QRect(190, 10, 181, 20))
        self.lessonName.setObjectName("lessonName")
        self.description = QtWidgets.QTextEdit(Form)
        self.description.setGeometry(QtCore.QRect(10, 30, 361, 181))
        self.description.setObjectName("description")
        self.createButton = QtWidgets.QPushButton(Form)
        self.createButton.setGeometry(QtCore.QRect(160, 220, 75, 23))
        self.createButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createButton.setObjectName("createButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", self.localeDATA["createSubject"]))
        self.teacherName.setPlaceholderText(_translate("Form", self.localeDATA["profName"]))
        self.lessonName.setPlaceholderText(_translate("Form", self.localeDATA["subjName"]))
        self.description.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.description.setPlaceholderText(_translate("Form", self.localeDATA["subjDescr"]))
        self.createButton.setText(_translate("Form", self.localeDATA["createButton"]))
import source_rc
