# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, localeDATA):
        self.localeDATA = localeDATA
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(295, 215)
        Form.setMinimumSize(QtCore.QSize(295, 215))
        Form.setMaximumSize(QtCore.QSize(295, 215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupName = QtWidgets.QLineEdit(Form)
        self.groupName.setGeometry(QtCore.QRect(10, 20, 261, 20))
        self.groupName.setObjectName("groupName")
        self.direction = QtWidgets.QLineEdit(Form)
        self.direction.setGeometry(QtCore.QRect(10, 50, 261, 20))
        self.direction.setObjectName("direction")
        self.CuratorName = QtWidgets.QLineEdit(Form)
        self.CuratorName.setGeometry(QtCore.QRect(10, 80, 261, 20))
        self.CuratorName.setObjectName("CuratorName")
        self.textCourse = QtWidgets.QLabel(Form)
        self.textCourse.setGeometry(QtCore.QRect(60, 110, 101, 21))
        self.textCourse.setObjectName("textCourse")
        self.course = QtWidgets.QSpinBox(Form)
        self.course.setGeometry(QtCore.QRect(10, 110, 42, 22))
        self.course.setMinimum(1)
        self.course.setMaximum(6)
        self.course.setProperty("value", 1)
        self.course.setObjectName("course")
        self.createGroup = QtWidgets.QPushButton(Form)
        self.createGroup.setGeometry(QtCore.QRect(90, 170, 111, 23))
        self.createGroup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createGroup.setObjectName("createGroup")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", self.localeDATA['createGroup']))
        self.groupName.setPlaceholderText(_translate("Form", self.localeDATA["groupName"]))
        self.direction.setPlaceholderText(_translate("Form", self.localeDATA["direction"]))
        self.CuratorName.setPlaceholderText(_translate("Form", self.localeDATA["curatorName"]))
        self.textCourse.setText(_translate("Form", self.localeDATA["course"]))
        self.createGroup.setText(_translate("Form", self.localeDATA["createGroup"]))
import source_rc
