# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editTask.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, localeDATA):
        self.localeDATA = localeDATA
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 71))
        self.label.setObjectName("label")
        self.taskDescription = QtWidgets.QPlainTextEdit(Form)
        self.taskDescription.setEnabled(True)
        self.taskDescription.setGeometry(QtCore.QRect(10, 100, 371, 151))
        self.taskDescription.setObjectName("taskDescription")
        self.Save = QtWidgets.QPushButton(Form)
        self.Save.setGeometry(QtCore.QRect(200, 270, 75, 23))
        self.Save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save.setObjectName("Save")
        self.lessonSelect = QtWidgets.QComboBox(Form)
        self.lessonSelect.setGeometry(QtCore.QRect(90, 10, 181, 21))
        self.lessonSelect.setObjectName("lessonSelect")
        self.deadline = QtWidgets.QDateEdit(Form)
        self.deadline.setGeometry(QtCore.QRect(90, 30, 110, 22))
        self.deadline.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 1), QtCore.QTime(0, 0, 0)))
        self.deadline.setObjectName("deadline")
        self.push_in = QtWidgets.QDateEdit(Form)
        self.push_in.setGeometry(QtCore.QRect(90, 60, 110, 22))
        self.push_in.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 1), QtCore.QTime(0, 0, 0)))
        self.push_in.setObjectName("push_in")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(120, 270, 75, 23))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", self.localeDATA["info_abTask"]))
        self.label.setText(_translate("Form", f"<html><head/><body><p>{self.localeDATA['subjectTranslate']}:</p><p>{self.localeDATA['short_deadlineText']} </p><p>{self.localeDATA['shortStart_notifying']}:</p></body></html>"))
        self.taskDescription.setPlaceholderText(_translate("Form", self.localeDATA["task_descr"]))
        self.Save.setText(_translate("Form", self.localeDATA["saveText"]))
        self.cancel.setText(_translate("Form", self.localeDATA["cancelText"]))
import source_rc
