# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LangChoose.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(321, 116)
        Form.setMinimumSize(QtCore.QSize(321, 116))
        Form.setMaximumSize(QtCore.QSize(321, 116))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 31))
        self.label.setObjectName("label")
        self.set_lang = QtWidgets.QComboBox(Form)
        self.set_lang.setGeometry(QtCore.QRect(10, 50, 301, 21))
        self.set_lang.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.set_lang.setStyleSheet("")
        self.set_lang.setObjectName("set_lang")
        self.cont = QtWidgets.QPushButton(Form)
        self.cont.setGeometry(QtCore.QRect(230, 80, 75, 23))
        self.cont.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cont.setObjectName("cont")
        self.machineTranslation_warn = QtWidgets.QLabel(Form)
        self.machineTranslation_warn.setGeometry(QtCore.QRect(10, 80, 221, 21))
        self.machineTranslation_warn.setObjectName("machineTranslation_warn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Выбор языка"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Choose your language</span></p></body></html>"))
        self.cont.setText(_translate("Form", "Продолжить"))
        self.machineTranslation_warn.setText(_translate("Form", "Присутствует машинный перевод!!"))
import source_rc
