ALTER TABLE langs ADD COLUMN authTitle TEXT DEFAULT ('Authorization');
ALTER TABLE langs ADD COLUMN loginText TEXT DEFAULT ('Login');
ALTER TABLE langs ADD COLUMN progrUpdateTitle TEXT DEFAULT ('Application update');
ALTER TABLE langs ADD COLUMN progrUpdateMessage TEXT DEFAULT ('saw table');
ALTER TABLE langs ADD COLUMN dataUpd_message TEXT DEFAULT ('Data was been updated.');
ALTER TABLE langs ADD COLUMN middleNameText TEXT DEFAULT ('Last name');
ALTER TABLE langs ADD COLUMN apply TEXT DEFAULT ('Apply');
ALTER TABLE langs ADD COLUMN failedConnection TEXT DEFAULT ('No network connection.\nNetwork services are not available');
ALTER TABLE langs ADD COLUMN nameText TEXT DEFAULT ('Name');
ALTER TABLE langs ADD COLUMN sectionGroup TEXT DEFAULT ('Group');
ALTER TABLE langs ADD COLUMN in_developing_txt TEXT DEFAULT ('In developing');
ALTER TABLE langs ADD COLUMN info_abTask TEXT DEFAULT ('Information about task');
ALTER TABLE langs ADD COLUMN logIn_Text TEXT DEFAULT ('LogIn');
ALTER TABLE langs ADD COLUMN auth_act TEXT DEFAULT ('Log In');
ALTER TABLE langs ADD COLUMN regText TEXT DEFAULT ('Registration');
ALTER TABLE langs ADD COLUMN passwordText TEXT DEFAULT ('Password');
ALTER TABLE langs ADD COLUMN professor TEXT DEFAULT ('Professor');
ALTER TABLE langs ADD COLUMN showPassword TEXT DEFAULT ('Show password');
ALTER TABLE langs ADD COLUMN len_description_Alert TEXT DEFAULT ('Enter more than four characters in the "task Content" column!!!');
ALTER TABLE langs ADD COLUMN logoutConfirmation TEXT DEFAULT ('Are you sure you want to log out of this account?');
ALTER TABLE langs ADD COLUMN updateTitleProgram TEXT DEFAULT ('Database update manager');
ALTER TABLE langs ADD COLUMN subjectTranslate TEXT DEFAULT ('Subject');
ALTER TABLE langs ADD COLUMN subjectAdd TEXT DEFAULT ('Lesson was been added');
ALTER TABLE langs ADD COLUMN noLessons_descrAlert TEXT DEFAULT ('There are no created disciplines. Create a discipline.');
ALTER TABLE langs ADD COLUMN groupTitle_of_app TEXT DEFAULT ('group of');
ALTER TABLE langs ADD COLUMN authError TEXT DEFAULT ('Authorization failed.');
ALTER TABLE langs ADD COLUMN unc_passwordError TEXT DEFAULT ('Invalid password.');
ALTER TABLE langs ADD COLUMN unc_loginError TEXT DEFAULT ('Invalid login.');
ALTER TABLE langs ADD COLUMN passwordError TEXT DEFAULT ('Enter password.');
ALTER TABLE langs ADD COLUMN openDatabaseLog TEXT DEFAULT ('Open database');
ALTER TABLE langs ADD COLUMN addGroup TEXT DEFAULT ('Group was been added.');
ALTER TABLE langs ADD COLUMN copyData_inBuffer_Log TEXT DEFAULT ('Copying table data to the buffer');
ALTER TABLE langs ADD COLUMN complLogin TEXT DEFAULT ('You have successfully logged in as');
ALTER TABLE langs ADD COLUMN deadlineText TEXT DEFAULT ('Deadline:');
ALTER TABLE langs ADD COLUMN short_deadlineText TEXT DEFAULT ('Deadline:');
ALTER TABLE langs ADD COLUMN copyDataLog TEXT DEFAULT ('Copying data');
ALTER TABLE langs ADD COLUMN addAccount_message TEXT DEFAULT ('Account was been added');
ALTER TABLE langs ADD COLUMN successAlert TEXT DEFAULT ('Successfully!');
ALTER TABLE langs ADD COLUMN okay TEXT DEFAULT ('OK');
ALTER TABLE langs ADD COLUMN delTask TEXT DEFAULT ('Delete task');
ALTER TABLE langs ADD COLUMN editText TEXT DEFAULT ('edit');
ALTER TABLE langs ADD COLUMN errorAlert TEXT DEFAULT ('Error.');
ALTER TABLE langs ADD COLUMN login_inDB_Error TEXT DEFAULT ('This username is already in the database.');
ALTER TABLE langs ADD COLUMN taskAdd TEXT DEFAULT ('Task was been added.');
ALTER TABLE langs ADD COLUMN exceptionAlert_msg TEXT DEFAULT ('Program was been terminated this exception:');
ALTER TABLE langs ADD COLUMN fromLog TEXT DEFAULT ('from');
ALTER TABLE langs ADD COLUMN ageTxt TEXT DEFAULT ('Age');
ALTER TABLE langs ADD COLUMN activateDarkTheme TEXT DEFAULT ('Dark theme on');
ALTER TABLE langs ADD COLUMN addTask TEXT DEFAULT ('Add task');
ALTER TABLE langs ADD COLUMN tasks_txt TEXT DEFAULT ('Tasks');
ALTER TABLE langs ADD COLUMN textGeneral TEXT DEFAULT ('General');
ALTER TABLE langs ADD COLUMN add_text TEXT DEFAULT ('Add');
ALTER TABLE langs ADD COLUMN deadline TEXT DEFAULT ('Deadline:');
ALTER TABLE langs ADD COLUMN start_notifying TEXT DEFAULT ('Start notifying');
ALTER TABLE langs ADD COLUMN shortStart_notifying TEXT DEFAULT ('Show in');
ALTER TABLE langs ADD COLUMN task_descr TEXT DEFAULT ('Task content');
ALTER TABLE langs ADD COLUMN group_t TEXT DEFAULT ('Group:');
ALTER TABLE langs ADD COLUMN newPassword TEXT DEFAULT ('New passsword');
ALTER TABLE langs ADD COLUMN resetPassword TEXT DEFAULT ('Reset your password');
ALTER TABLE langs ADD COLUMN settings TEXT DEFAULT ('Settings');
ALTER TABLE langs ADD COLUMN direction TEXT DEFAULT ('Profession');
ALTER TABLE langs ADD COLUMN networkSettings_section TEXT DEFAULT ('Network settings');
ALTER TABLE langs ADD COLUMN data_editionAlert TEXT DEFAULT ('Are you sure you want to change the data?');
ALTER TABLE langs ADD COLUMN securitySection TEXT DEFAULT ('Security');
ALTER TABLE langs ADD COLUMN unlock TEXT DEFAULT ('Unlock');
ALTER TABLE langs ADD COLUMN createProfileButton TEXT DEFAULT ('Create profile');
ALTER TABLE langs ADD COLUMN curatorName TEXT DEFAULT ('saw table');
ALTER TABLE langs ADD COLUMN profName TEXT DEFAULT ('saw table');
ALTER TABLE langs ADD COLUMN subjName TEXT DEFAULT ('Subject');
ALTER TABLE langs ADD COLUMN subjDescr TEXT DEFAULT ('Subject description');
ALTER TABLE langs ADD COLUMN createGroup TEXT DEFAULT ('Create group');
ALTER TABLE langs ADD COLUMN createSubject TEXT DEFAULT ('Create subject');
ALTER TABLE langs ADD COLUMN deletedTask_message TEXT DEFAULT ('Task was been deleted.');
ALTER TABLE langs ADD COLUMN deleteTask_message TEXT DEFAULT ('Do you want to delete this task?');
ALTER TABLE langs ADD COLUMN wantProtect TEXT DEFAULT ('Protect my profile with a password');
ALTER TABLE langs ADD COLUMN passsword TEXT DEFAULT ('Password');
ALTER TABLE langs ADD COLUMN show_passsword TEXT DEFAULT ('Show password');
ALTER TABLE langs ADD COLUMN passwReseted TEXT DEFAULT ('Your password was been reseted');
ALTER TABLE langs ADD COLUMN passwEdited TEXT DEFAULT ('Your password was been edited');
ALTER TABLE langs ADD COLUMN typeOf_training TEXT DEFAULT ('Type of training');
ALTER TABLE langs ADD COLUMN budget TEXT DEFAULT ('Budget');
ALTER TABLE langs ADD COLUMN сommerce TEXT DEFAULT ('Commerce');
ALTER TABLE langs ADD COLUMN currentTasks TEXT DEFAULT ('Current tasks');
ALTER TABLE langs ADD COLUMN completeTask TEXT DEFAULT ('Completed');
ALTER TABLE langs ADD COLUMN course TEXT DEFAULT ('Course');
ALTER TABLE langs ADD COLUMN groupName TEXT DEFAULT ('Group name');
ALTER TABLE langs ADD COLUMN hereLearn TEXT DEFAULT ('Full-time');
ALTER TABLE langs ADD COLUMN distantLearn TEXT DEFAULT ('In absentia');
ALTER TABLE langs ADD COLUMN saveText TEXT DEFAULT ('Save');
ALTER TABLE langs ADD COLUMN cancelText TEXT DEFAULT ('Cancel');
ALTER TABLE langs ADD COLUMN createButton TEXT DEFAULT ('Create');
ALTER TABLE langs ADD COLUMN requestError TEXT DEFAULT ('Request denied');
ALTER TABLE langs ADD COLUMN rewriteFormsAlert TEXT DEFAULT ('Do you really want to create a profile?');
ALTER TABLE langs ADD COLUMN openTableLog TEXT DEFAULT ('Opening table');
ALTER TABLE langs ADD COLUMN exit TEXT DEFAULT ('Exit');