# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, localeDATA):
        self.localeDATA = localeDATA
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/sources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 361, 51))
        self.label.setObjectName("label")
        self.taskDescription = QtWidgets.QTextBrowser(Form)
        self.taskDescription.setEnabled(True)
        self.taskDescription.setGeometry(QtCore.QRect(10, 60, 371, 191))
        self.taskDescription.setObjectName("taskDescription")
        self.close = QtWidgets.QPushButton(Form)
        self.close.setGeometry(QtCore.QRect(170, 270, 75, 23))
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setObjectName("close")
        self.edit = QtWidgets.QPushButton(Form)
        self.edit.setGeometry(QtCore.QRect(354, 270, 41, 23))
        self.edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit.setObjectName("edit")
        self.delButton = QtWidgets.QPushButton(Form)
        self.delButton.setGeometry(QtCore.QRect(10, 270, 111, 23))
        self.delButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delButton.setObjectName("delButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", self.localeDATA["info_abTask"]))
        self.label.setText(_translate("Form", "<html><head/><body><p>Предмет: lesson course курс<br/>Преподаватель: teacher<br/>Срок: до DD.MM.YYYY</p></body></html>"))
        self.close.setText(_translate("Form", self.localeDATA["okay"]))
        self.edit.setText(_translate("Form", self.localeDATA["editText"]))
        self.delButton.setText(_translate("Form", self.localeDATA["delTask"]))
import source_rc
